name: Suma Simple Workflow

on: [push]

jobs:
  sum:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Suma de dos numeros
      run: |
        number1=5
        number2=10
        sum=$((number1 + number2))
        echo "La suma de $number1 y $number2 es $sum"
